# Copyright (C) 2020  Matthew Glazar
# See end of file for extended copyright information.

name: check error docs
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_format:
    name: check error docs
    runs-on: ubuntu-latest
    container: ghcr.io/quick-lint/quick-lint-js-github-website-builder:v4
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: C++ configure
        run: emcmake cmake -S . -B build -G Ninja
      - name: C++ build
        run: emmake cmake --build build --target quick-lint-js-vscode quick-lint-js-vscode-licenses
      - name: C++ install
        run: emmake cmake --install build --component vscode --prefix website/public/demo

      - name: JS configure
        run: cd website && yarn install --production

      - name: check docs
        run: node website/tools/check-error-documentation.mjs
      - name: check diagnostics
        run: node website/tools/check-diagnostic-messages.mjs

# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew Glazar
#
# This file is part of quick-lint-js.
#
# quick-lint-js is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# quick-lint-js is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with quick-lint-js.  If not, see <https://www.gnu.org/licenses/>.
